version: '1'
services:
  if-api-service:
    image: 'clyi/engineer-course'
    labels: 
      co.elastic.logs/enabled: true
    ports:
      - '8080:8080'
    depends_on:
      - if-db
      - elk
      
  if-db:
    image: 'mongo:latest' 
    ports:
      - '27017:27017'
    labels: 
      co.elastic.logs/enabled: false
    volumes:
      - 'data-vol:/data/db'

  elk:
    image: 'clyi/elk'
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'
    labels: 
      co.elastic.logs/enabled: false
    volumes:
      - 'elk-vol:/var/lib/elasticsearch'
    healthcheck:
      test: curl -s http://elk:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  filebeat:
    image: 'docker.elastic.co/beats/filebeat:8.4.3'
    user: 'root'
    labels: 
      co.elastic.logs/enabled: false
    depends_on:
      elk:
        condition: 'service_healthy'
    environment:
      - 'setup.kibana.host=elk:5601'
      - 'output.elasticsearch.hosts=["elk:9200"]'
      - 'output.elasticsearch.allow_older_versions=true'
    volumes:
      - './filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  zoo1:
    image: 'confluentinc/cp-zookeeper:latest'
    restart: unless-stopped
    labels: 
      co.elastic.logs/enabled: false
    ports:
      - '2181:2181'
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOO_SERVERS: 'server.1=zoo1:2888:3888'
    volumes:
      - './full-stack/zoo1/data:/data'
      - './full-stack/zoo1/datalog:/datalog'
  
  kafka1:
    image: confluentinc/cp-kafka:latest
    labels: 
      co.elastic.logs/enabled: false
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092'
      KAFKA_ZOOKEEPER_CONNECT: 'zoo1:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - './full-stack/kafka1/data:/var/lib/kafka/data'
    depends_on:
      - zoo1

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    labels: 
      co.elastic.logs/enabled: false
    ports:
      - '8081:8080'
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_READONLY=true
    depends_on:
      - kafka1

volumes:
  data-vol:
  elk-vol: